// Generated by the protocol buffer compiler.  DO NOT EDIT!

package communication;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class BasicMsg extends
      com.google.protobuf.GeneratedMessage {
    // Use BasicMsg.newBuilder() to construct.
    private BasicMsg() {}
    
    private static final BasicMsg defaultInstance = new BasicMsg();
    public static BasicMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public BasicMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return communication.Messages.internal_static_communication_BasicMsg_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return communication.Messages.internal_static_communication_BasicMsg_fieldAccessorTable;
    }
    
    // required int32 msgId = 1;
    private boolean hasMsgId;
    private int msgId_ = 0;
    public boolean hasMsgId() { return hasMsgId; }
    public int getMsgId() { return msgId_; }
    
    // repeated bytes data = 2;
    private java.util.List<com.google.protobuf.ByteString> data_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.ByteString> getDataList() {
      return data_;
    }
    public int getDataCount() { return data_.size(); }
    public com.google.protobuf.ByteString getData(int index) {
      return data_.get(index);
    }
    
    public static communication.Messages.BasicMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static communication.Messages.BasicMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static communication.Messages.BasicMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static communication.Messages.BasicMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static communication.Messages.BasicMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static communication.Messages.BasicMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static communication.Messages.BasicMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static communication.Messages.BasicMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(communication.Messages.BasicMsg prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using communication.Messages.BasicMsg.newBuilder()
      private Builder() {}
      
      communication.Messages.BasicMsg result = new communication.Messages.BasicMsg();
      
      @Override
      protected communication.Messages.BasicMsg internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new communication.Messages.BasicMsg();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return communication.Messages.BasicMsg.getDescriptor();
      }
      
      public communication.Messages.BasicMsg getDefaultInstanceForType() {
        return communication.Messages.BasicMsg.getDefaultInstance();
      }
      
      public communication.Messages.BasicMsg build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private communication.Messages.BasicMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public communication.Messages.BasicMsg buildPartial() {
        if (result.data_ != java.util.Collections.EMPTY_LIST) {
          result.data_ =
            java.util.Collections.unmodifiableList(result.data_);
        }
        communication.Messages.BasicMsg returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required int32 msgId = 1;
      public boolean hasMsgId() {
        return result.hasMsgId();
      }
      public int getMsgId() {
        return result.getMsgId();
      }
      public Builder setMsgId(int value) {
        result.hasMsgId = true;
        result.msgId_ = value;
        return this;
      }
      public Builder clearMsgId() {
        result.hasMsgId = false;
        result.msgId_ = 0;
        return this;
      }
      
      // repeated bytes data = 2;
      public java.util.List<com.google.protobuf.ByteString> getDataList() {
        return java.util.Collections.unmodifiableList(result.data_);
      }
      public int getDataCount() {
        return result.getDataCount();
      }
      public com.google.protobuf.ByteString getData(int index) {
        return result.getData(index);
      }
      public Builder setData(int index, com.google.protobuf.ByteString value) {
        result.data_.set(index, value);
        return this;
      }
      public Builder addData(com.google.protobuf.ByteString value) {
        if (result.data_.isEmpty()) {
          result.data_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        result.data_.add(value);
        return this;
      }
      public Builder addAllData(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        if (result.data_.isEmpty()) {
          result.data_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        super.addAll(values, result.data_);
        return this;
      }
      public Builder clearData() {
        result.data_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      communication.Messages.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_communication_BasicMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_communication_BasicMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\016messages.proto\022\rcommunication\"\'\n\010Basic" +
      "Msg\022\r\n\005msgId\030\001 \002(\005\022\014\n\004data\030\002 \003(\014";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_communication_BasicMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_communication_BasicMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_communication_BasicMsg_descriptor,
              new java.lang.String[] { "MsgId", "Data", },
              communication.Messages.BasicMsg.class,
              communication.Messages.BasicMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
